#!/usr/bin/env python3
"""
Unit tests for the Saleae harness signal parser and SR_00 evaluation.

Run from extras/tests/saleae_based:
    python3 -m unittest discover -s scripts/tests -v
"""

import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[1]
COMMON = SCRIPTS.parents[0] / "common"
sys.path.insert(0, str(SCRIPTS))

import analyze_csv  # noqa: E402
import run_hardware  # noqa: E402
import run_tests  # noqa: E402
import signal_parser as sp  # noqa: E402
import vcd_fixtures as vf  # noqa: E402

# The QINFO values the scenarios are planned against. Nothing here measures
# them; run_hardware only needs them to size the capture window.
_FAKE_DUT = vf.Dut()


def square(period_samples, high_samples, n_samples):
    """1/0 waveform: high for the first high_samples of each period."""
    return [1 if (i % period_samples) < high_samples else 0
            for i in range(n_samples)]


class TestSignalParser(unittest.TestCase):
    def test_square_wave_metrics(self):
        # 1 MHz, period 1000 samples (=1 ms -> 1 kHz), 10 % duty.
        samples = square(period_samples=1000, high_samples=100, n_samples=5000)
        m = sp.channel_metrics(samples, 1_000_000)
        self.assertAlmostEqual(m.frequency_hz, 1000.0, delta=1.0)
        self.assertAlmostEqual(m.duty_cycle_percent, 10.0, delta=0.5)
        # Starts HIGH, so the first pulse has no rising edge in-capture:
        # 4 rising edges over 5000 samples.
        self.assertEqual(m.step_count, 4)
        self.assertAlmostEqual(m.avg_high_us, 100.0, delta=0.5)
        self.assertTrue(
            sp.period_defects(m.inter_step_us, 1000.0)["ok"])

    def test_period_defects_flags_merged_and_dropped(self):
        # Two steps collapsed into one 500 us period, then a 2000 us gap
        # because one step never arrived.
        d = sp.period_defects([1000.0, 500.0, 1000.0, 2000.0], 1000.0)
        self.assertEqual(d["n_short"], 1)
        self.assertEqual(d["n_long"], 1)
        self.assertFalse(d["ok"])

    def test_step_count_defects(self):
        self.assertTrue(sp.step_count_defects(10, 10)["ok"])
        extra = sp.step_count_defects(11, 10)
        self.assertEqual(extra["extra_steps"], 1)
        self.assertFalse(extra["ok"])
        missing = sp.step_count_defects(9, 10)
        self.assertEqual(missing["missing_steps"], 1)
        self.assertFalse(missing["ok"])

    def test_pulse_widths_are_full_intervals(self):
        samples = square(1000, 250, 3000)
        m = sp.channel_metrics(samples, 1_000_000)
        for w in m.high_widths_us:
            self.assertAlmostEqual(w, 250.0, delta=0.5)
        for w in m.low_widths_us:
            self.assertAlmostEqual(w, 750.0, delta=0.5)

    def test_detect_edges(self):
        self.assertEqual(sp.detect_edges([0, 0, 1, 1, 0, 1]),
                         [(2, 1), (4, 0), (5, 1)])

    def test_dir_to_first_step(self):
        dir_samples = [0] * 1000 + [1] * 100
        step_samples = [0] * 1050 + [1] * 10 + [0] * 40
        delays = sp.dir_to_first_step_us(dir_samples, step_samples, 1_000_000)
        self.assertEqual(len(delays), 1)
        self.assertAlmostEqual(delays[0], 50.0, delta=0.5)

    def test_cross_channel_skew(self):
        a = [0] * 10 + [1] * 10 + [0] * 100
        b = [0] * 260 + [1] * 10 + [0] * 100
        skew = sp.cross_channel_skew_us({"A": a, "B": b}, 1_000_000)
        self.assertAlmostEqual(skew, 250.0, delta=0.5)

    def test_parse_rate(self):
        self.assertEqual(sp.parse_rate("1 MHz"), 1_000_000)
        self.assertEqual(sp.parse_rate(" 4MHz"), 4_000_000)
        self.assertEqual(sp.parse_rate("20 kHz"), 20_000)
        self.assertEqual(sp.parse_rate("1000000 Hz"), 1_000_000)

    def test_load_csv_roundtrip(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "capture.csv")
            with open(path, "w") as f:
                f.write("; CSV generated by libsigrok\n")
                f.write("; Samplerate: 1 MHz\n")
                f.write("logic,logic\n")
                f.write("0,1\n1,0\n0,1\n")
            channels, rate = sp.load_csv(path)
            self.assertEqual(rate, 1_000_000)
            self.assertEqual(channels["D0"], [0, 1, 0])
            self.assertEqual(channels["D1"], [1, 0, 1])

    def test_parse_timescale(self):
        self.assertAlmostEqual(sp.parse_timescale("1 us"), 1000.0)
        self.assertAlmostEqual(sp.parse_timescale("100 ps"), 0.1)
        self.assertAlmostEqual(sp.parse_timescale("1 ns"), 1.0)

    def test_load_vcd_expands_changes(self):
        # 1 MHz -> sigrok writes a 1 us timescale; changes only, no repeats.
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "capture.vcd")
            with open(path, "w") as f:
                f.write("$timescale 1 us $end\n")
                f.write("$scope module libsigrok $end\n")
                f.write("$var wire 1 ! D0 $end\n")
                f.write("$var wire 1 \" D1 $end\n")
                f.write("$upscope $end\n$enddefinitions $end\n")
                f.write("#0 1! 0\"\n")
                f.write("#2 0!\n")
                f.write("#5 1!\n")
            channels, rate = sp.load_vcd(path)
            self.assertEqual(rate, 1_000_000)
            self.assertEqual(list(channels["D0"]), [1, 1, 0, 0, 0, 1])
            self.assertEqual(list(channels["D1"]), [0, 0, 0, 0, 0, 0])

    def test_vcd_is_padded_to_the_declared_capture_length(self):
        """A flat tail must survive the trip through VCD.

        A VCD records value changes only, so a channel that stops changing
        early ends the file short of the real capture. Without the sidecar the
        two cases -- a line that went quiet, and a recording that ran out --
        are indistinguishable, which is what made every SR_25 capture look
        like it stopped on its final pulse.
        """
        import json
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            vcd = Path(tmp) / "c.vcd"
            # Shaped like sigrok's own output, including the $comment that
            # carries the acquisition rate, so the real parse path is exercised.
            vcd.write_text(
                "$comment\n  Acquisition with 2/8 channels at 1 MHz\n"
                "$end\n"
                "$timescale 1 ns $end\n"
                "$scope logic $end\n"
                "$var wire 1 ! D0 $end\n"
                "$upscope $end\n"
                "$enddefinitions $end\n"
                "#0 1!\n")
            bare, _ = sp.load_vcd(str(vcd))
            self.assertEqual(len(bare["D0"]), 1, "no sidecar means no padding")

            (Path(tmp) / "c.meta").write_text(json.dumps(
                {"samples": 500, "sample_rate": 1_000_000}))
            padded, rate = sp.load_vcd(str(vcd))
            self.assertEqual(rate, 1_000_000)
            self.assertEqual(len(padded["D0"]), 500)
            self.assertEqual(set(padded["D0"]), {1}, "the flat level is kept")

    def test_unreadable_sidecar_is_ignored(self):
        """A corrupt sidecar must not make a capture unloadable."""
        import tempfile
        with tempfile.TemporaryDirectory() as tmp:
            vcd = Path(tmp) / "c.vcd"
            vcd.write_text("$timescale 1 ns $end\n"
                          "$scope logic $end\n"
                          "$var wire 1 ! D0 $end\n"
                          "$upscope $end\n"
                          "$enddefinitions $end\n"
                          "#0 1!\n")
            (Path(tmp) / "c.meta").write_text("{not json")
            channels, _ = sp.load_vcd(str(vcd))
            self.assertEqual(list(channels["D0"]), [1])

    def test_sr_to_vcd_matches_sr(self):
        """sigrok-cli .sr -> VCD must reproduce the samples exactly."""
        sr_path = Path(__file__).resolve().parents[2] / "capture.sr"
        if not sr_path.exists() or not shutil.which("sigrok-cli"):
            self.skipTest("no capture.sr or sigrok-cli")
        with tempfile.TemporaryDirectory() as tmp:
            vcd = os.path.join(tmp, "capture.vcd")
            result = subprocess.run(
                ["sigrok-cli", "-I", "srzip", "-i", str(sr_path),
                 "-O", "vcd", "-o", vcd],
                capture_output=True, text=True, timeout=60)
            self.assertEqual(result.returncode, 0, result.stderr)
            sr_channels, sr_rate = sp.load_sr(str(sr_path))
            vcd_channels, vcd_rate = sp.load_vcd(vcd)
            self.assertEqual(vcd_rate, sr_rate)
            # The VCD holds changes only, so it can end before the last
            # constant stretch of the capture.
            n = min(len(samples) for samples in vcd_channels.values())
            for name, samples in sr_channels.items():
                # bytearray, not list: a 24 MS/s capture is 96M samples and a
                # list of ints would cost ~770 MB per channel.
                self.assertEqual(bytes(samples[:n]), bytes(vcd_channels[name]),
                                 name)


class TestSR00(unittest.TestCase):
    DUTY_MS = [50, 100, 150, 200, 250, 300, 350, 400]

    def _channels(self, period_samples=1000, n_periods=3, invert=None):
        channels = {}
        for i, high in enumerate(self.DUTY_MS):
            name = f"D{i}"
            samples = square(period_samples, high, period_samples * n_periods)
            if invert == name:
                samples = [0 if s else 1 for s in samples]
            channels[name] = samples
        return channels

    def test_all_channels_pass(self):
        channels = self._channels()
        passed, results = analyze_csv.evaluate_sr00(channels, 1000)
        self.assertTrue(passed)
        for i, high in enumerate(self.DUTY_MS):
            self.assertAlmostEqual(results[f"D{i}"]["duty_cycle_percent"],
                                   high / 10.0, delta=0.5)
            self.assertTrue(results[f"D{i}"]["passed"])

    def test_inverted_channel_detected(self):
        channels = self._channels(invert="D0")  # 5 % -> 95 %
        passed, results = analyze_csv.evaluate_sr00(channels, 1000)
        self.assertFalse(passed)
        self.assertTrue(results["D0"]["inverted"])
        self.assertFalse(results["D0"]["passed"])

    def test_wrong_frequency_fails(self):
        # 500 samples/period at 1000 Hz -> 2 Hz
        channels = self._channels(period_samples=500)
        passed, _ = analyze_csv.evaluate_sr00(channels, 1000)
        self.assertFalse(passed)


# Every CONFIG the harness can emit, as (logical config, native driver) pairs.
# The firmware's grammar is not exercised by any unit test -- it needs a board --
# so what is pinned here is that the host never produces a line the firmware
# would refuse, and never names no driver at all.
CONFIG_CASES = [
    (cfg, native)
    for cfg in run_tests.CONFIGS
    for native in ("rmt_v2", "timer", "pio", "mcpwm_pcnt")
]

# The names the firmware's parse_driver() knows about. A driver it does not know
# is refused, so a typo here would surface as a refused CONFIG and an ERR that
# reads like a hardware fault.
FIRMWARE_DRIVERS = {
    "rmt", "rmt_v2", "mcpwm", "mcpwm_pcnt", "i2s", "i2s_direct", "i2s_mux",
    "timer", "pio",
}


class TestConfigGrammar(unittest.TestCase):
    def test_wire_line_names_every_driver(self):
        for cfg, native in CONFIG_CASES:
            wire = run_tests.config_wire(cfg, native)
            tokens = wire.split()
            self.assertEqual(tokens[0], "CONFIG", wire)
            # count, then one driver per stepper, then the pin mode.
            self.assertTrue(tokens[1].isdigit(), wire)
            drivers = tokens[2].split(",")
            self.assertEqual(len(drivers), int(tokens[1]), wire)
            self.assertIn(tokens[3], ("dir", "nodir"), wire)
            self.assertTrue(all(drivers), f"empty driver name in {wire!r}")

    def test_no_driver_is_ever_auto(self):
        for cfg, native in CONFIG_CASES:
            for driver in run_tests.config_drivers(cfg, native):
                self.assertIn(driver, FIRMWARE_DRIVERS,
                              f"{cfg} sends {driver!r}, which CONFIG refuses")

    def test_driver_names_resolve_per_architecture(self):
        # One driver per stepper is the invariant; the count comes from the
        # config, not from the length of a driver list the caller padded.
        self.assertEqual(run_tests.config_drivers("1ch", "timer"), ["timer"])
        self.assertEqual(run_tests.config_drivers("2ch", "pio"), ["pio", "pio"])
        self.assertEqual(run_tests.config_drivers("mixed_rmt_mcpwm", "rmt_v2"),
                         ["rmt", "mcpwm_pcnt"])

    def test_scenarios_only_use_known_configs(self):
        for sid, (cfg, *_rest) in run_tests.SCENARIOS.items():
            self.assertIn(cfg, run_tests.CONFIGS,
                          f"{sid} names config {cfg!r}, which has no CONFIG")

    def test_firmware_has_no_implicit_driver_choice(self):
        # The firmware is not unit-tested, so this is the only place the rule
        # can be checked without a board: SA_AUTO and DRIVER_DONT_CARE would
        # both reintroduce a driver nobody named.
        source = (COMMON / "saleae_app.cpp").read_text()
        code = "\n".join(
            line for line in source.splitlines()
            if not line.lstrip().startswith("//"))
        self.assertNotIn("SA_AUTO", code)
        self.assertNotIn("DRIVER_DONT_CARE", code)

    def test_firmware_refuses_the_superseded_presets(self):
        # `CONFIG 1ch` is the old vocabulary. It must not reach a connected
        # stepper, and the count token is validated whole so atol cannot read
        # the leading digit and quietly configure one stepper.
        source = (COMMON / "saleae_app.cpp").read_text()
        self.assertIn('*end != \'\\0\'', source)
        for name in ("1ch", "2ch", "4ch_rmt", "4ch_mcpwm"):
            self.assertNotIn(f'strcmp(name, "{name}")', source)

    def test_config_line_fits_the_firmware_line_buffer(self):
        # The firmware reads a line into a fixed buffer and takes each argument
        # with a bounded sscanf width. A CONFIG the host generates that does not
        # fit is truncated on the way in and refused with a misleading "no such
        # driver" on the half-cut last name -- so the budget is checked here,
        # where it can be changed when the stepper count rises.
        source = (COMMON / "saleae_app.cpp").read_text()
        line_max = int(re.search(r"#define SALEAE_LINE_MAX (\d+)",
                                 source).group(1))
        # Every buffer sscanf writes into, paired with the width the format
        # claims for it. A buffer smaller than its own width is a buffer
        # overflow, and a width smaller than the buffer is a silent truncation
        # that reads as a refusal -- both have to be ruled out, and only
        # checking one of them is what made an earlier version of this test
        # pass while the bug it was written for was present.
        buffers = {name: int(size) for name, size in re.findall(
            r"char (arg\d)\[(\d+)\]", source)}
        widths = [int(w) for w in re.findall(r"%(\d+)s", source)]
        self.assertEqual(len(widths), len(buffers) + 1,
                         "sscanf format and argument buffers disagree")
        for (name, size), width in zip(buffers.items(), widths[1:]):
            self.assertEqual(size - 1, width,
                             f"{name}[{size}] but sscanf says %{width}s")
        widest = max(buffers.values()) - 1

        count = max(run_tests.CONFIGS[c][0] for c in run_tests.CONFIGS)
        for driver in FIRMWARE_DRIVERS:
            line = f"CONFIG {count} {','.join([driver] * count)} dir"
            self.assertLessEqual(len(line), line_max - 1,
                                 f"{line!r} does not fit SALEAE_LINE_MAX")
            self.assertLessEqual(count * len(driver) + count - 1, widest,
                                 f"a {count}x {driver!r} driver list is "
                                 f"truncated by the argument width")


class TestBoardCommands(unittest.TestCase):
    """What the runner actually puts on the wire.

    Nothing else here talks to a board, and the one thing that goes wrong
    silently is a line that is *nearly* right: `CONFIG CONFIG 1 rmt_v2 dir` was
    refused by the firmware on all 25 scenarios at once and read as a wiring
    fault rather than as the doubled keyword it was. A fake board that records
    what it was asked is the only place that shows up without one.
    """

    def _sent_to_board(self, scenario, dut_driver="rmt_v2"):
        """Run one scenario's CONFIG against a fake board; return the lines."""
        sent = []

        class FakeCapture:
            returncode = 0

            def communicate(self, timeout=None):
                return ("", "")

        def fake_capture(*_args, **_kwargs):
            return FakeCapture()

        wire, channels, mask = run_hardware.wire_plan(scenario, dut_driver)
        with mock.patch.object(run_hardware, "send",
                               lambda ser, line, wait=1.0:
                               sent.append(line) or "OK CONFIG"), \
                mock.patch.object(run_hardware, "cold_boot",
                                  lambda port: mock.Mock()), \
                mock.patch.object(run_hardware.subprocess, "Popen",
                                  fake_capture), \
                mock.patch("time.sleep", lambda _s: None):
            run_hardware.run_segments(
                [(8, 640, True)], wire, channels, mask, "t",
                _FAKE_DUT.info())
        return sent

    def test_config_is_sent_exactly_once(self):
        for scenario in sorted(run_tests.SCENARIOS,
                               key=lambda s: int(s.split("_")[1])):
            sent = self._sent_to_board(scenario)
            self.assertTrue(sent, scenario)
            first = sent[0]
            self.assertEqual(first, run_tests.config_wire(
                run_tests.SCENARIOS[scenario][0], "rmt_v2"),
                f"{scenario} sends {first!r}")
            self.assertEqual(first.count("CONFIG"), 1, first)
            self.assertEqual(first.split()[0], "CONFIG", first)


if __name__ == "__main__":
    unittest.main(verbosity=2)
