#!/usr/bin/env python3
"""
Unit tests for the Saleae harness signal parser and SR_00 evaluation.

Run from extras/tests/saleae_based:
    python3 -m unittest discover -s scripts/tests -v
"""

import os
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(SCRIPTS))

import analyze_csv  # noqa: E402
import signal_parser as sp  # noqa: E402


def square(period_samples, high_samples, n_samples):
    """1/0 waveform: high for the first high_samples of each period."""
    return [1 if (i % period_samples) < high_samples else 0
            for i in range(n_samples)]


class TestSignalParser(unittest.TestCase):
    def test_square_wave_metrics(self):
        # 1 MHz, period 1000 samples (=1 ms -> 1 kHz), 10 % duty.
        samples = square(period_samples=1000, high_samples=100, n_samples=5000)
        m = sp.channel_metrics(samples, 1_000_000)
        self.assertAlmostEqual(m.frequency_hz, 1000.0, delta=1.0)
        self.assertAlmostEqual(m.duty_cycle_percent, 10.0, delta=0.5)
        self.assertEqual(m.glitch_count, 0)
        # Starts HIGH, so the first pulse has no rising edge in-capture:
        # 4 rising edges over 5000 samples.
        self.assertEqual(m.step_count, 4)
        self.assertAlmostEqual(m.avg_high_us, 100.0, delta=0.5)

    def test_pulse_widths_are_full_intervals(self):
        samples = square(1000, 250, 3000)
        m = sp.channel_metrics(samples, 1_000_000)
        for w in m.high_widths_us:
            self.assertAlmostEqual(w, 250.0, delta=0.5)
        for w in m.low_widths_us:
            self.assertAlmostEqual(w, 750.0, delta=0.5)

    def test_detect_edges(self):
        self.assertEqual(sp.detect_edges([0, 0, 1, 1, 0, 1]),
                         [(2, 1), (4, 0), (5, 1)])

    def test_dir_to_first_step(self):
        dir_samples = [0] * 1000 + [1] * 100
        step_samples = [0] * 1050 + [1] * 10 + [0] * 40
        delays = sp.dir_to_first_step_us(dir_samples, step_samples, 1_000_000)
        self.assertEqual(len(delays), 1)
        self.assertAlmostEqual(delays[0], 50.0, delta=0.5)

    def test_cross_channel_skew(self):
        a = [0] * 10 + [1] * 10 + [0] * 100
        b = [0] * 260 + [1] * 10 + [0] * 100
        skew = sp.cross_channel_skew_us({"A": a, "B": b}, 1_000_000)
        self.assertAlmostEqual(skew, 250.0, delta=0.5)

    def test_parse_rate(self):
        self.assertEqual(sp.parse_rate("1 MHz"), 1_000_000)
        self.assertEqual(sp.parse_rate(" 4MHz"), 4_000_000)
        self.assertEqual(sp.parse_rate("20 kHz"), 20_000)
        self.assertEqual(sp.parse_rate("1000000 Hz"), 1_000_000)

    def test_load_csv_roundtrip(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "capture.csv")
            with open(path, "w") as f:
                f.write("; CSV generated by libsigrok\n")
                f.write("; Samplerate: 1 MHz\n")
                f.write("logic,logic\n")
                f.write("0,1\n1,0\n0,1\n")
            channels, rate = sp.load_csv(path)
            self.assertEqual(rate, 1_000_000)
            self.assertEqual(channels["D0"], [0, 1, 0])
            self.assertEqual(channels["D1"], [1, 0, 1])


class TestSR00(unittest.TestCase):
    DUTY_MS = [50, 100, 150, 200, 250, 300, 350, 400]

    def _channels(self, period_samples=1000, n_periods=3, invert=None):
        channels = {}
        for i, high in enumerate(self.DUTY_MS):
            name = f"D{i}"
            samples = square(period_samples, high, period_samples * n_periods)
            if invert == name:
                samples = [0 if s else 1 for s in samples]
            channels[name] = samples
        return channels

    def test_all_channels_pass(self):
        channels = self._channels()
        passed, results = analyze_csv.evaluate_sr00(channels, 1000)
        self.assertTrue(passed)
        for i, high in enumerate(self.DUTY_MS):
            self.assertAlmostEqual(results[f"D{i}"]["duty_cycle_percent"],
                                   high / 10.0, delta=0.5)
            self.assertTrue(results[f"D{i}"]["passed"])

    def test_inverted_channel_detected(self):
        channels = self._channels(invert="D0")  # 5 % -> 95 %
        passed, results = analyze_csv.evaluate_sr00(channels, 1000)
        self.assertFalse(passed)
        self.assertTrue(results["D0"]["inverted"])
        self.assertFalse(results["D0"]["passed"])

    def test_wrong_frequency_fails(self):
        # 500 samples/period at 1000 Hz -> 2 Hz
        channels = self._channels(period_samples=500)
        passed, _ = analyze_csv.evaluate_sr00(channels, 1000)
        self.assertFalse(passed)


if __name__ == "__main__":
    unittest.main(verbosity=2)
