
SRC=$(wildcard ../../src/*) $(wildcard src/*)

TRACES=-at OCF1A=trace@0x36/0x02
TRACES+=-at OCR1AL=trace@0x88/0xff
TRACES+=-at OCR1AH=trace@0x89/0xff
TRACES+=-at StepA=trace@0x25/0x02
TRACES+=-at FOC1A=trace@0x82/0x80

FIRMWARE=".pio/build/avr/firmware.elf"
DEVICE="atmega328p"

test: .tested

.tested:	x.vcd expect.txt
	gawk -f ../eval.awk x.vcd
	cat expect.txt
	cat result.txt
	cmp result.txt expect.txt && touch .tested

x.vcd:	$(SRC) ../run_avr platformio.ini
	~/.platformio/penv/bin/pio run -e avr
	../run_avr $(FIRMWARE) -m $(DEVICE) -o x.vcd $(TRACES)

clean:
	rm -fR .pio .tested x.vcd result.txt
