#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""
Generate platformio.ini and GitHub workflow files from build_matrix.yaml

Usage:
    ./generate_build_configs.py                    # Generate all files
    ./generate_build_configs.py --platformio       # Generate only platformio.ini
    ./generate_build_configs.py --workflows        # Generate only workflow files
    ./generate_build_configs.py --dry-run          # Print to stdout instead of writing
"""

import argparse
from pathlib import Path
from typing import Any

import yaml

SCRIPT_DIR = Path(__file__).parent.resolve()
ROOT_DIR = SCRIPT_DIR.parent.parent
CI_DIR = ROOT_DIR / "extras" / "ci"
WORKFLOWS_DIR = ROOT_DIR / ".github" / "workflows"
BUILD_MATRIX_YAML = CI_DIR / "build_matrix.yaml"


def load_yaml() -> dict[str, Any]:
    with open(BUILD_MATRIX_YAML) as f:
        return yaml.safe_load(f)


def version_to_suffix(version: str) -> str:
    return f"_V{version}"


def resolve_env(
    env_config: dict[str, Any], templates: dict[str, Any]
) -> dict[str, Any]:
    resolved = {}
    if "template" in env_config:
        template_name = env_config["template"]
        if template_name not in templates:
            raise ValueError(f"Unknown template: {template_name}")
        resolved.update(templates[template_name])
    resolved.update(env_config)
    return resolved


def expand_versioned_environments(data: dict[str, Any]) -> dict[str, Any]:
    templates = data.get("templates", {})
    environments = dict(data.get("environments", {}))
    versioned = data.get("versioned_environments", {})

    for group_name, group_config in versioned.items():
        template_name = group_config.get("template")
        base_config = {}
        if template_name:
            base_config = dict(templates.get(template_name, {}))
        base_config.update(
            {
                k: v
                for k, v in group_config.items()
                if k not in ("template", "versions", "prefix")
            }
        )

        name_prefix = group_config.get("prefix", group_name)

        for version in group_config.get("versions", []):
            version_underscore = version.replace(".", "_")
            env_name = f"{name_prefix}_V{version_underscore}"
            env_config = dict(base_config)
            env_config["platform_version"] = version
            environments[env_name] = env_config

    return environments


def generate_platformio_ini(data: dict[str, Any]) -> str:
    lines = [
        "; THIS FILE IS AUTOGENERATED - DO NOT EDIT",
        "; Source: extras/ci/build_matrix.yaml",
        "; Regenerate: ./extras/scripts/generate_build_configs.py --platformio",
        ";",
        "; PlatformIO Project Configuration File",
        ";",
        ";   Build options: build flags, source filter",
        ";   Upload options: custom upload port, speed and extra flags",
        ";   Library options: dependencies, extra library storages",
        ";   Advanced options: extra scripting",
        ";",
        "; Please visit documentation for the other options and examples",
        "; https://docs.platformio.org/page/projectconf.html",
        ";",
        "; use build_flags = -E -DM",
        "; to get all preprocessor symbols in .pio/build/xx/src/StepperDemo.cpp.o",
        ";",
        "[platformio]",
        "",
    ]

    templates = data.get("templates", {})
    environments = expand_versioned_environments(data)

    for env_name, env_config in environments.items():
        resolved = resolve_env(env_config, templates)
        lines.append(f"[env:{env_name}]")

        if "platform_version" in resolved:
            platform_name = resolved.get("platform", "espressif32")
            lines.append(f"platform = {platform_name} @ {resolved['platform_version']}")
        elif "platform" in resolved:
            lines.append(f"platform = {resolved['platform']}")

        if "board" in resolved:
            lines.append(f"board = {resolved['board']}")

        if "framework" in resolved:
            lines.append(f"framework = {resolved['framework']}")

        if "build_flags" in resolved or "build_flags_extra" in resolved:
            flags = list(resolved.get("build_flags", []))
            flags.extend(resolved.get("build_flags_extra", []))
            if flags:
                flags_str = " ".join(flags)
                lines.append(f"build_flags = {flags_str}")

        if "board_build_f_cpu" in resolved:
            lines.append(f"board_build.f_cpu = {resolved['board_build_f_cpu']}")

        if "lib_extra_dirs" in resolved:
            lines.append(f"lib_extra_dirs = {resolved['lib_extra_dirs']}")

        if "board_build_core" in resolved:
            lines.append(f"board_build.core = {resolved['board_build_core']}")

        if "board_build_mcu" in resolved:
            lines.append(f"board_build.mcu = {resolved['board_build_mcu']}")

        if "board_upload_psram_length" in resolved:
            lines.append(
                f"board_upload.psram_length = {resolved['board_upload_psram_length']}"
            )

        lines.append("")

    return "\n".join(lines)


def generate_workflow_yml(workflow_name: str, workflow_config: dict[str, Any]) -> str:
    lines = [
        "# AUTOGENERATED FILE - DO NOT EDIT",
        "# Source: extras/ci/build_matrix.yaml",
        "# Regenerate: ./extras/scripts/generate_build_configs.py --workflows",
        "",
    ]

    if "comments" in workflow_config:
        for comment in workflow_config["comments"]:
            lines.append(f"# {comment}")
        lines.append("")

    lines.extend(
        [
            f"name: {workflow_config['name']}",
            "",
        ]
    )

    if "on" in workflow_config:
        lines.append("on:")
        on_config = workflow_config["on"]
        if "push" in on_config:
            lines.append("  push:")
            lines.append("    branches: [ master ]")
        if "pull_request" in on_config:
            lines.append("  pull_request:")
            lines.append("    branches: [ master ]")
        lines.append("")

    lines.extend(
        [
            "jobs:",
            "  build:",
            "    strategy:",
            "      matrix:",
            "        version:",
        ]
    )

    for version in workflow_config["matrix"]:
        if version.startswith("#"):
            lines.append(f"          {version}")
        else:
            lines.append(f"          - {version}")

    lines.extend(
        [
            "",
            "    runs-on: ubuntu-latest",
            "",
            "    steps:",
            "    - name: Checkout",
            "      uses: actions/checkout@v5",
            "    - name: Make directories",
            "      run: bash extras/scripts/build-pio-dirs.sh",
            "    - name: Build on PlatformIO",
            f"      run: bash extras/scripts/{workflow_config['script']} ${{{{ matrix.version }}}}",
            "",
        ]
    )

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate build configuration files")
    parser.add_argument(
        "--platformio", action="store_true", help="Generate platformio.ini"
    )
    parser.add_argument(
        "--workflows", action="store_true", help="Generate workflow YAML files"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print to stdout instead of writing files",
    )
    args = parser.parse_args()

    if not args.platformio and not args.workflows:
        args.platformio = True
        args.workflows = True

    data = load_yaml()

    if args.platformio:
        content = generate_platformio_ini(data)
        if args.dry_run:
            print(f"=== {CI_DIR / 'platformio.ini'} ===")
            print(content)
        else:
            output_path = CI_DIR / "platformio.ini"
            output_path.write_text(content)
            print(f"Generated {output_path}")

    if args.workflows:
        workflows = data.get("workflows", {})
        for workflow_name, workflow_config in workflows.items():
            content = generate_workflow_yml(workflow_name, workflow_config)
            output_path = WORKFLOWS_DIR / f"build_{workflow_name}_examples_matrix.yml"
            if args.dry_run:
                print(f"\n=== {output_path} ===")
                print(content)
            else:
                output_path.write_text(content)
                print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
