// Autogenerated by extras/gen_pmf_const/main
// DO NOT EDIT
#ifndef POORMANFLOATCONST_H
#define POORMANFLOATCONST_H

#include <PoorManFloat.h>

// PMF_CONST_1 = 0.000000  0 = 0x0000
#define PMF_CONST_1 ((pmf_logarithmic)0x0000)
// => converted back => 1.00

// PMF_CONST_3_DIV_2 = 299.500793  300 = 0x012c
#define PMF_CONST_3_DIV_2 ((pmf_logarithmic)0x012c)
// => converted back => 1.50

// PMF_CONST_128E12 = 23993.925781  23994 = 0x5dba
#define PMF_CONST_128E12 ((pmf_logarithmic)0x5dba)
// => converted back => 128012783714304.00

// PMF_CONST_16E6 = 12252.962891  12253 = 0x2fdd
#define PMF_CONST_16E6 ((pmf_logarithmic)0x2fdd)
// => converted back => 16000799.00

// PMF_CONST_500 = 4590.481445  4590 = 0x11ee
#define PMF_CONST_500 ((pmf_logarithmic)0x11ee)
// => converted back => 499.67

// PMF_CONST_1000 = 5102.481445  5102 = 0x13ee
#define PMF_CONST_1000 ((pmf_logarithmic)0x13ee)
// => converted back => 999.35

// PMF_CONST_2000 = 5614.481445  5614 = 0x15ee
#define PMF_CONST_2000 ((pmf_logarithmic)0x15ee)
// => converted back => 1998.70

// PMF_CONST_32000 = 7662.481445  7662 = 0x1dee
#define PMF_CONST_32000 ((pmf_logarithmic)0x1dee)
// => converted back => 31979.14

// PMF_CONST_16E6_DIV_SQRT_OF_2 = 11996.962891  11997 = 0x2edd
#define PMF_CONST_16E6_DIV_SQRT_OF_2 ((pmf_logarithmic)0x2edd)
// => converted back => 11314274.00

// PMF_CONST_21E6 = 12453.830078  12454 = 0x30a6
#define PMF_CONST_21E6 ((pmf_logarithmic)0x30a6)
// => converted back => 21004844.00

// PMF_CONST_42000 = 7863.348145  7863 = 0x1eb7
#define PMF_CONST_42000 ((pmf_logarithmic)0x1eb7)
// => converted back => 41980.21

// PMF_CONST_21E6_DIV_SQRT_OF_2 = 12197.830078  12198 = 0x2fa6
#define PMF_CONST_21E6_DIV_SQRT_OF_2 ((pmf_logarithmic)0x2fa6)
// => converted back => 14852668.00

// PMF_CONST_2205E11 = 24395.660156  24396 = 0x5f4c
#define PMF_CONST_2205E11 ((pmf_logarithmic)0x5f4c)
// => converted back => 220601734135808.00

// PMF_CONST_UINT32_MAX = 16384.000000  16384 = 0x4000
#define PMF_CONST_UINT32_MAX ((pmf_logarithmic)0x4000)
// => converted back => 4294967296.00

// PMF_CONST_UINT16_MAX = 8191.988770  8192 = 0x2000
#define PMF_CONST_UINT16_MAX ((pmf_logarithmic)0x2000)
// => converted back => 65536.00

// used in PoorManFloat.cpp as example
//
// PMF_CONST_15373 = 7120.953125  7121 = 0x1bd1
#define PMF_CONST_15373 ((pmf_logarithmic)0x1bd1)
// => converted back => 15373.98
#endif
