name: Run pc-based tests

on:
  push:
    branches: [ master, refactor ]
  pull_request:
    branches: [ master, refactor ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -C extras/tests/pc_based
