name: Run pc-based tests

on:
  push:
    branches: [ master, naxes ]
  pull_request:
    branches: [ master, naxes ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: make
      run: make -C extras/tests/pc_based
