#!/usr/bin/env python3
"""
config/test_cases.py — Test case definitions for Saleae test harness.

Defines all 41 test cases (SR_00–SR_40) with metadata:
  - test_id: SR_XX identifier
  - name: Human-readable name
  - category: Test category
  - steppers: Number of steppers involved
  - requires_hardware: Whether this test requires physical hardware
  - esp32_only: Whether this test runs on ESP32 chips only
  - parameters: Test-specific parameters with defaults
"""

TEST_CASES = [
    # Connection Verification (no PC-based equivalent)
    {
        "test_id": "SR_00",
        "name": "port_toggle",
        "category": "connection",
        "steppers": 0,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"pin": 2, "hz": 1},
        "description": "Each Step/Dir pin toggles at a known frequency (1 Hz square wave). No stepper motion.",
    },
    # Basic Ramp Tests (mapped from PC-based test_01–test_05)
    {
        "test_id": "SR_01",
        "name": "basic_move_forward",
        "category": "ramp",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "speed_us": 400},
        "description": "Move N steps forward at constant speed.",
    },
    {
        "test_id": "SR_02",
        "name": "basic_move_reverse",
        "category": "ramp",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "speed_us": 400},
        "description": "Move N steps backward.",
    },
    {
        "test_id": "SR_03",
        "name": "mixed_direction_ramp",
        "category": "ramp",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps_array": [500, 300, 500, 300], "speed_us": 400},
        "description": "Alternating forward/reverse moves.",
    },
    {
        "test_id": "SR_04",
        "name": "acceleration_ramp",
        "category": "ramp",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 5000, "start_speed_us": 400, "end_speed_us": 40, "acceleration": 10000},
        "description": "Accelerate from rest to max speed and decelerate.",
    },
    {
        "test_id": "SR_05",
        "name": "speed_profile_multi_phase",
        "category": "ramp",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 3000, "speeds_array": [400, 40, 400], "phases": 3},
        "description": "Multi-phase speed: slow → fast → slow.",
    },
    # Timing Precision Tests (mapped from PC-based test_06–test_12)
    {
        "test_id": "SR_06",
        "name": "direction_to_step_delay",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"speed_us": 400},
        "description": "Measure dir→first-step delay at various speeds.",
    },
    {
        "test_id": "SR_07",
        "name": "step_pulse_width_at_speed",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"speed_us": 400},
        "description": "Measure pulse width at various speeds.",
    },
    {
        "test_id": "SR_08",
        "name": "duty_cycle_symmetry",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"speed_us": 400},
        "description": "Check high/low symmetry across speeds.",
    },
    {
        "test_id": "SR_09",
        "name": "abrupt_speed_change",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"high_speed_us": 40, "low_speed_us": 400},
        "description": "Jump from max speed to min speed (and back).",
    },
    {
        "test_id": "SR_10",
        "name": "min_tick_boundary",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {},
        "description": "Test at MIN_CMD_TICKS boundary.",
    },
    {
        "test_id": "SR_11",
        "name": "max_speed_boundary",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000},
        "description": "Test at maximum speed (minimum ticks).",
    },
    {
        "test_id": "SR_12",
        "name": "queue_fill_latency",
        "category": "timing",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000},
        "description": "Measure time from enqueue to first step pulse during burst.",
    },
    # Synchronized Start Tests (mapped from PC-based test_13–test_17)
    {
        "test_id": "SR_13",
        "name": "sync_start_same_tick",
        "category": "sync",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000},
        "description": "4 steppers start simultaneously.",
    },
    {
        "test_id": "SR_14",
        "name": "sync_start_delayed_start",
        "category": "sync",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "delays_us": [0, 100, 200, 300]},
        "description": "Steppers start with staggered delays.",
    },
    {
        "test_id": "SR_15",
        "name": "sync_start_different_speeds",
        "category": "sync",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "speeds_us": [400, 200, 100, 50]},
        "description": "Steppers start together but at different speeds.",
    },
    {
        "test_id": "SR_16",
        "name": "sync_start_n_axis",
        "category": "sync",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "targets": [1000, 500, -500, -1000]},
        "description": "Multi-axis synchronized move to different targets.",
    },
    {
        "test_id": "SR_17",
        "name": "sync_start_cross_driver",
        "category": "sync",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {"steps": 1000},
        "description": "Steppers use different drivers (RMT + MCPWM).",
    },
    # Queue Management Tests (mapped from PC-based test_18–test_24)
    {
        "test_id": "SR_18",
        "name": "queue_full_behavior",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000},
        "description": "Fill queue to capacity, then try to enqueue more.",
    },
    {
        "test_id": "SR_19",
        "name": "queue_empty_prevention",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000},
        "description": "Ensure queue never empties during move.",
    },
    {
        "test_id": "SR_20",
        "name": "moveTimed_accuracy",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "duration_ms": 1000},
        "description": "Move to position in specified time.",
    },
    {
        "test_id": "SR_21",
        "name": "moveTimed_direction_change",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "mid_point": 500},
        "description": "moveTimed with direction change mid-move.",
    },
    {
        "test_id": "SR_22",
        "name": "pause_command_insertion",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000, "pause_ticks": 160000},
        "description": "Pause commands (steps=0) between step commands.",
    },
    {
        "test_id": "SR_23",
        "name": "queue_overflow_cycling",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"cycles": 100},
        "description": "Rapid enqueue/dequeue cycling.",
    },
    {
        "test_id": "SR_24",
        "name": "moveTimed_drift_check",
        "category": "queue",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"cycles": 10, "steps": 1000},
        "description": "Repeated moveTimed cycles (Issue #370 regression).",
    },
    # Driver-Specific Tests
    {
        "test_id": "SR_25",
        "name": "rmt_buffer_split",
        "category": "driver",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "Verify RMT V1 two-part buffer split at command boundary.",
    },
    {
        "test_id": "SR_26",
        "name": "rmt_v2_fill_encoder",
        "category": "driver",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "Verify RMT V2 fill encoder output.",
    },
    {
        "test_id": "SR_27",
        "name": "i2s_direct_timing",
        "category": "driver",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {"steps": 1000},
        "description": "Verify I2S direct output timing.",
    },
    {
        "test_id": "SR_28",
        "name": "i2s_mux_timing",
        "category": "driver",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {"steps": 1000},
        "description": "Verify I2S mux output timing.",
    },
    {
        "test_id": "SR_29",
        "name": "mcpwm_pcnt_sync",
        "category": "driver",
        "steppers": 2,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "Verify MCPWM timer sync across units.",
    },
    {
        "test_id": "SR_30",
        "name": "rmt_sync_manager",
        "category": "driver",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "Verify RMT TX sync manager (ESP32/ESP32-S3).",
    },
    # Channel Configuration Stress Tests
    {
        "test_id": "SR_31",
        "name": "8ch_step_only_max_speed",
        "category": "stress",
        "steppers": 8,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "8 steppers, all at max speed.",
    },
    {
        "test_id": "SR_32",
        "name": "7ch_shared_dir_consistency",
        "category": "stress",
        "steppers": 7,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {},
        "description": "7 steppers sharing one Dir line.",
    },
    {
        "test_id": "SR_33",
        "name": "mixed_driver_interference",
        "category": "stress",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "RMT + MCPWM + I2S running simultaneously.",
    },
    {
        "test_id": "SR_34",
        "name": "i2s_extender_scaling",
        "category": "stress",
        "steppers": 6,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {"stepper_count": 6},
        "description": "4→8 steppers on I2S extender.",
    },
    {
        "test_id": "SR_35",
        "name": "channel_reassignment",
        "category": "stress",
        "steppers": 4,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "Reassign steppers to different drivers at runtime.",
    },
    # Edge Cases and Error Conditions
    {
        "test_id": "SR_36",
        "name": "gpio_pin_reuse",
        "category": "edge",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"pin": 2},
        "description": "Step/Dir pins shared with other peripherals.",
    },
    {
        "test_id": "SR_37",
        "name": "interrupt_load",
        "category": "edge",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": True,
        "parameters": {},
        "description": "High interrupt load from other peripherals.",
    },
    {
        "test_id": "SR_38",
        "name": "power_sag_recovery",
        "category": "edge",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {},
        "description": "Simulate power sag during move. (Requires programmable/current-limited supply.)",
    },
    {
        "test_id": "SR_39",
        "name": "emergency_stop",
        "category": "edge",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 1000},
        "description": "Force stop during active move.",
    },
    {
        "test_id": "SR_40",
        "name": "overflow_wraparound",
        "category": "edge",
        "steppers": 1,
        "requires_hardware": True,
        "esp32_only": False,
        "parameters": {"steps": 4000000000},
        "description": "32-bit position counter overflow.",
    },
]


def get_test_case(test_id):
    """Get test case by ID (e.g., 'SR_01')."""
    for tc in TEST_CASES:
        if tc["test_id"] == test_id:
            return tc
    return None


def list_test_cases():
    """List all test case IDs."""
    return [tc["test_id"] for tc in TEST_CASES]


def get_test_cases_by_category(category):
    """Get test cases filtered by category."""
    return [tc for tc in TEST_CASES if tc["category"] == category]